name: url-shortner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: url_shortner_test
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_CONN_STR: postgres://postgres@localhost:5432/url_shortner_test?sslmode=disable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432; do echo waiting for postgres...; sleep 1; done

      - name: Create test table
        run: |
          psql -h localhost -U postgres -d url_shortner_test -c "
          CREATE TABLE IF NOT EXISTS urls (
            id SERIAL PRIMARY KEY,
            tenant TEXT NOT NULL,
            shortcode TEXT UNIQUE NOT NULL,
            original_url TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT NOW()
          );"

      - name: Run handler tests
        run: go test -v ./handlers

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag
        id: meta
        run: echo "tag=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest
            ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ steps.meta.outputs.tag }}
